[package]
name = "wread-data-mongodb"
version = "0.12.1"
authors = ["Saju Thankappan <sajuthankappan@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "read and write data for mongodb"
homepage = "https://github.com/sajuthankappan/wread-data-mongodb-rs"
repository = "https://github.com/sajuthankappan/wread-data-mongodb-rs"
readme = "README.md"
keywords = ["mongodb"]
categories = ["database"]

[features]
default = ["read"]
read = []
write = []

[dependencies]
futures = "0.3.5"
log = "0.4.11"
serde = { version = "1.0.115", features = ["derive"] }

[dependencies.mongodb]
version = "1.1.0"